{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.mysql_root_password | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.mysql_database | b64enc | quote }}
  MYSQL_USER: {{ .Values.mysql.mysql_user | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.mysql_password | b64enc | quote }}
{{- end }}
