apiVersion: v1
kind: Service
metadata:
  name: {{ include "media-wiki-demo.fullname" . }}
  labels:
    {{- include "media-wiki-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "media-wiki-demo.selectorLabels" . | nindent 4 }}

---
{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "media-wiki-demo.fullname" . }}-mysql
  labels:
    {{- include "media-wiki-demo.selectorLabels" . | nindent 8 }}
spec:
  ports:
  - name: {{ include "media-wiki-demo.fullname" . }}-mysql
    port: 3306
  clusterIP: None
  selector:
    {{- include "media-wiki-demo.selectorLabels" . | nindent 6 }}
{{- end }}
